services:
  app:
    ports: !reset []
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=loja_carros
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_PASSWORD}

  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: loja_carros
    ports: !reset []

  nginx:
    ports: !override
      - "8081:80"
